#!/bin/sh

# change to directory sources are in
cd `dirname \`command -v "$0"\``

mkdir /tmp/GitHub.wdgt
cp -a * /tmp/GitHub.wdgt
cp -a /tmp/GitHub.wdgt .
rm -rf /tmp/GitHub.wdgt
cp -a GitHub.wdgt ~/Library/Widgets
rm -rf GitHub.wdgt
open ~/Library/Widgets/GitHub.wdgt
