/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "%s does not appear to be a valid RSS or Atom feed.": "%s does not appear to be a valid RSS or Atom feed.",
    "%s new": "%s new",
    "Article Length": "Article Length",
    "Done": "Done",
    "Feed URLs: ": "Feed URLs: ",
    "Invalid Feed": "Invalid Feed",
    "Loading...": "Loading...",
    "My RSS Feed": "My RSS Feed",
    "New URL: ": "New URL: ",
    "No Feed Specified": "No Feed Specified",
    "No Items Found": "No Items Found",
    "No items matched the search terms.": "No items matched the search terms.",
    "Nothing To Display": "Nothing To Display",
    "Please specify a valid feed URL.": "Please specify a valid feed URL.",
    "Reset": "Reset",
    "Set": "Set",
    "The feed does not contain any entries within the specified criteria.": "The feed does not contain any entries within the specified criteria.",
    "The feed does not contain any entries.": "The feed does not contain any entries.",
    "HTTP Error Getting Feed for ": "HTTP Error Getting Feed for ",
    "you": "you"
};
